<?php
namespace App\Http\Controllers;
use App\Mail\BookDeliveryMail; use App\Models\Book; use App\Models\BookOrder; use App\Services\BookPdfDeliveryService; use FedaPay\FedaPay; use FedaPay\Transaction; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\Mail; use Illuminate\Support\Str; use Illuminate\View\View;
class BookPurchaseController extends Controller {
 public function index(): View{return view('books.index',['books'=>Book::query()->where('is_published',true)->latest()->get()]);}
 public function show(Book $book): View{abort_unless($book->is_published,404);return view('books.show',compact('book'));}
 public function begin(Request $request,Book $book): RedirectResponse{abort_unless($book->is_published,404);if(!$request->user())return redirect()->route('login',['redirect_to'=>route('books.begin',$book)]);return redirect()->route('books.payment',$book);}
 public function payment(Book $book): View{abort_unless($book->is_published,404);return view('books.payment',compact('book'));}
 public function checkout(Request $request,Book $book): RedirectResponse { abort_unless($book->is_published,404); $order=BookOrder::create(['reference'=>(string)Str::uuid(),'book_id'=>$book->id,'user_id'=>$request->user()->id,'amount'=>$book->price,'unlock_code'=>Str::upper(Str::random(12))]); try { FedaPay::setApiKey((string)config('services.fedapay.secret_key'));FedaPay::setEnvironment((string)config('services.fedapay.environment','sandbox'));$transaction=Transaction::create(['amount'=>$book->price,'currency'=>['iso'=>$book->currency],'description'=>'Livre : '.$book->title,'callback_url'=>route('books.callback',$order),'merchant_reference'=>$order->reference,'customer'=>['firstname'=>$request->user()->prenom ?: $request->user()->fullName(),'lastname'=>$request->user()->nom ?: '.','email'=>$request->user()->email]]);$checkout=$transaction->generateToken();$order->update(['provider_transaction_id'=>(string)$transaction->id,'checkout_url'=>$checkout->url]);return redirect()->route('books.checkout.redirect',$order); } catch(\Throwable $e){$order->update(['status'=>'failed']);return back()->withErrors(['payment'=>'Paiement indisponible. Veuillez réessayer.']);}}
 public function redirect(BookOrder $order): View {abort_unless($order->user_id===auth()->id(),403);return view('books.redirect',compact('order'));}
 public function callback(BookOrder $order,BookPdfDeliveryService $delivery): RedirectResponse {abort_unless($order->user_id===auth()->id(),403);FedaPay::setApiKey((string)config('services.fedapay.secret_key'));FedaPay::setEnvironment((string)config('services.fedapay.environment','sandbox'));try{$transaction=Transaction::retrieve($order->provider_transaction_id);if(!$transaction->wasPaid())return redirect()->route('books.show',$order->book)->withErrors(['payment'=>'Paiement en attente de confirmation.']);$order->update(['status'=>'paid','paid_at'=>now()]);$delivery->secure($order->fresh('book'));Mail::to($order->user->email)->send(new BookDeliveryMail($order->fresh(['book','user'])));$order->update(['delivered_at'=>now()]);return redirect()->route('books.show',$order->book)->with('book_success','Paiement confirmé : votre livre et son code ont été envoyés par e-mail.');}catch(\Throwable $e){return redirect()->route('books.show',$order->book)->withErrors(['payment'=>'Confirmation en cours. Vérifiez votre e-mail dans quelques instants.']);}}
}
